### ISSUE TITLE
Use with vDAQ

### ISSUE THREAD

**Issue by ablot** [BaselLaserMouse/ScanImageTools#3]
I would like to adapt the ai_recorder to use it with the vidrio vDAQ. I was planning on just forking and replacing the Ni components for sake of simplicity but before doing that I had two questions:

- are you still using/developing the ai_recorder module?
- if so do you have a suggestion to refractor and use either vDAQ or NI cards or should I just go ahead and make my incompatible fork

**Comment by raacampbell** [comment]
I do use it and others do too so a refactor to handle either scenario would be good. We have two vDAQs in the lab now so in future this problem will crop up again.

**Comment by ablot** [comment]
I'll give it a try. I haven't found much documentation about the vDAQ API. Let me know if you stumble across something useful.

**Comment by ablot** [comment]
I struggled a lot to understand what I was doing but it seems that the vDAQ behaves very weirdly below 3000 Hz.

Here is a plot of the number of samples in 100ms vs the sampling rate of the task. I'm obviously expecting a straight line with y = x/10, but it is true only above 3kHz. It is not some weird random task duration/measurement effect as 2 run (black dot and red circles) have the exact same measure

![vDAQ_weirdness](https://user-images.githubusercontent.com/2701493/100617808-eb988000-3312-11eb-91aa-1aec6e345500.jpg)

**Comment by raacampbell** [comment]
Oh... I think ask Vidrio. 
The way I approached the DAQmx API was to write a bunch of examples as I went about learning it. Then I did stuff with it. If you are so motivated, that would also be very helpful here. The examples I wrote for the Vidrio DAQmx wrapper are at: https://github.com/tenss/MATLAB_DAQmx_examples/tree/master/code/%2Bvidrio

**Comment by ablot** [comment]
I have something that works well enough to try (with the >3kHz limitation). I'll re-open if I run into unexpected issues.

**Comment by ablot** [comment]
Answer from vidriotech for futur reference:

There is a minimum sample rate for the AI functions based on the system clock and the counter depth used to trigger the sample.  If you need 2kHz samples, you could set the sample rate to 4kHz and discard every second sample.
Amer Atrash, PhD
